using Godot;
using Perigee.Sim;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Perigee;

/// <summary>
/// The soundscape (GDD §18): four synth layers that mix by what the player is doing (orbit pad, launch swell, docking pulse,
/// storm motif, silence when the career is over or insolvent), an engine whose roar follows throttle and air density
/// (a muffled structural rumble in vacuum), pump and reentry loops, and one-shots for staging, docking, chutes, legs,
/// touchdown, crashes, radio beeps, cash and warnings. Every file is generated by <c>tools/audio/build.py</c>.
/// </summary>
public partial class Audio : Node
{
    public static Audio? I;
    const string Dir = "res://assets/audio/";
    public static readonly string[] Music = { "music_pad", "music_swell", "music_pulse", "music_storm" };
    public static readonly string[] Loops = { "engine_air", "engine_vac", "sfx_pump", "sfx_reentry" };
    public static readonly string[] Shots = { "stage", "dock", "undock", "beep", "chute", "legs", "touchdown", "crash", "cash", "warn", "click" };

    readonly Dictionary<string, AudioStream> _bank = new();
    readonly Dictionary<string, AudioStreamPlayer> _players = new();
    readonly Dictionary<string, float> _level = new();
    readonly List<AudioStreamPlayer> _shots = new();
    public Main Game = null!;
    public int Loaded => _bank.Count;
    public IReadOnlyDictionary<string, float> Levels => _level;
    public IReadOnlyDictionary<string, float> Target => _target;
    Dictionary<string, float> _target = new();
    public string? LastShot; public int ShotsPlayed;
    bool _lastLegs; bool _lastChute; StormPhase _lastStorm; int _lastCompleted = -1; double _lastSales = -1; int _lastWorldHash;

    public override void _Ready()
    {
        I = this;
        foreach (var m in Music) Load(m, true);
        foreach (var l in Loops) Load(l, true);
        foreach (var s in Shots) Load("sfx_" + s, false);
        foreach (var name in Music.Concat(Loops))
        {
            var p = new AudioStreamPlayer { Bus = name.StartsWith("music") ? "Music" : "SFX", VolumeDb = -80f };
            if (_bank.TryGetValue(name, out var st)) p.Stream = st;
            AddChild(p); _players[name] = p; _level[name] = 0f;
            if (p.Stream != null) p.Play();   // all loops run from t=0 together so the music layers stay in phase
        }
    }

    public override void _ExitTree()
    {
        foreach (var p in _players.Values) { p.Stop(); p.Stream = null; }
        foreach (var p in _shots) { p.Stop(); p.Stream = null; }
        _bank.Clear();
        if (I == this) I = null;
    }

    void Load(string name, bool loop)
    {
        string path = Dir + name + ".ogg";
        if (!ResourceLoader.Exists(path)) return;
        var stream = GD.Load<AudioStream>(path);
        if (stream is AudioStreamOggVorbis ogg) ogg.Loop = loop;
        _bank[name] = stream;
    }

    /// <summary>Plays a one-shot (stage, dock, undock, beep, chute, legs, touchdown, crash, cash, warn, click).</summary>
    public void Play(string shot, string bus = "SFX")
    {
        LastShot = shot; ShotsPlayed++;
        if (!_bank.TryGetValue("sfx_" + shot, out var stream)) return;
        var p = _shots.FirstOrDefault(x => !x.Playing);
        if (p == null) { if (_shots.Count >= 12) return; p = new AudioStreamPlayer(); AddChild(p); _shots.Add(p); }
        p.Bus = bus; p.Stream = stream; p.Play();
    }
    public void Click() => Play("click", "UI");

    /// <summary>Sim events from the game's tick loop.</summary>
    public void OnEvent(SimEvent e)
    {
        switch (e.Kind)
        {
            case SimEventKind.Staging: Play("stage"); break;
            case SimEventKind.Docked: Play("dock"); break;
            case SimEventKind.Undocked: Play("undock"); break;
            case SimEventKind.Landed: Play("touchdown"); break;
            case SimEventKind.Crashed: case SimEventKind.PartDestroyed: Play("crash"); break;
            case SimEventKind.Recovered: Play("cash"); break;
        }
    }

    /// <summary>The mix for a game state, as linear levels per loop (pure, so the self-test can assert on it).</summary>
    public static Dictionary<string, float> Mix(World? w, bool paused)
    {
        var m = new Dictionary<string, float>();
        foreach (var k in Music.Concat(Loops)) m[k] = 0f;
        if (w == null) { m["music_pad"] = 0.35f; return m; }
        if (w.GameOver || !double.IsNaN(w.InsolventSince)) return m;   // silence on the insolvency screen (GDD §18)
        var a = w.Active;
        bool physics = a is { Destroyed: false, Mode: CraftMode.Active or CraftMode.Landed };
        float swell = 0, pulse = 0, storm = w.Storm != StormPhase.None ? 1f : 0f;
        if (a != null && !a.Destroyed)
        {
            if (physics && a.Throttle > 0 && w.T - a.LaunchTime < 150) swell = 1f;
            if (a.TargetCraft >= 0 && w.Find(a.TargetCraft) is { Destroyed: false } t && t.BodyId == a.BodyId && (w.AbsolutePosition(t) - w.AbsolutePosition(a)).Length <= World.LoadedBubble) pulse = 1f;
        }
        bool busy = swell > 0 || pulse > 0 || storm > 0;
        m["music_pad"] = busy ? 0.6f : 1f; m["music_swell"] = swell; m["music_pulse"] = pulse; m["music_storm"] = storm;
        if (paused || a == null || a.Destroyed || !physics) return m;
        var body = w.Sys[a.BodyId];
        double alt = a.Pos.Length - body.Radius;
        double pr = body.Atmo?.PressureRatio(alt) ?? 0;
        double thrust = 0, max = 0;
        foreach (var p in a.Parts) if (!p.Destroyed && p.Def.Engine != null && p.Running) { thrust += p.LastThrust; max += p.Def.Engine.ThrustVac; }
        float thr = max > 0 ? (float)Math.Clamp(thrust / max, 0, 1) : 0f;
        float air = (float)Math.Sqrt(pr);
        m["engine_air"] = thr * air;
        m["engine_vac"] = thr * (1 - air) * 0.7f;
        m["sfx_pump"] = a.Pumps.Count > 0 ? 0.8f : 0f;
        double temp = a.Parts.Where(p => !p.Destroyed).Select(p => p.Temp).DefaultIfEmpty(0).Max();
        m["sfx_reentry"] = (float)Math.Clamp((temp - 600) / 700, 0, 1);
        return m;
    }

    public override void _Process(double delta)
    {
        var w = Game?.World;
        bool paused = Game == null || Game.MenuOpen || Game.Paused || Game.InBuilder;
        _target = Mix(w, paused);
        foreach (var (name, target) in _target)
        {
            float rate = name.StartsWith("music") ? 1.5f : name.StartsWith("engine") ? 8f : 4f;
            float cur = _level[name];
            cur += (target - cur) * Math.Min(1f, (float)delta * rate);
            _level[name] = cur;
            var p = _players[name];
            p.VolumeDb = cur < 0.002f ? -80f : Mathf.LinearToDb(cur);
            if (name == "engine_air" || name == "engine_vac") p.PitchScale = 0.85f + 0.3f * cur;
        }
        if (w == null || paused) return;
        // Transitions the sim does not announce as events.
        var a = w.Active;
        if (w.GetHashCode() != _lastWorldHash) { _lastWorldHash = w.GetHashCode(); _lastLegs = a?.LegsDown ?? false; _lastChute = false; _lastStorm = w.Storm; _lastCompleted = -1; _lastSales = -1; }
        if (a != null && !a.Destroyed)
        {
            bool legs = a.LegsDown; if (legs != _lastLegs) { Play("legs"); _lastLegs = legs; }
            bool chute = a.Parts.Any(p => !p.Destroyed && p.ChuteRamp > 0); if (chute && !_lastChute) Play("chute"); _lastChute = chute;
        }
        if (w.Storm != _lastStorm) { if (w.Storm == StormPhase.Warning) Play("warn"); _lastStorm = w.Storm; }
        int done = w.Contracts.Count(c => c.State == ContractState.Completed);
        if (_lastCompleted >= 0 && done > _lastCompleted) { Play("beep"); Play("cash"); }
        _lastCompleted = done;
        double sales = w.CareerStats.TryGetValue("sales", out var s) ? s : 0;
        if (_lastSales >= 0 && sales > _lastSales) Play("cash");
        _lastSales = sales;
    }
}
